package com.appsys.pojo;

import java.util.Date;

public class AdPromotion {
/**
 * This field was generated by MyBatis Generator.
 * This field corresponds to the database column ad_promotion.id
 *
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
private Long id;

/**
 * This field was generated by MyBatis Generator.
 * This field corresponds to the database column ad_promotion.appId
 *
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
private Long appid;

/**
 * This field was generated by MyBatis Generator.
 * This field corresponds to the database column ad_promotion.adPicPath
 *
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
private String adpicpath;

/**
 * This field was generated by MyBatis Generator.
 * This field corresponds to the database column ad_promotion.adPV
 *
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
private Long adpv;

/**
 * This field was generated by MyBatis Generator.
 * This field corresponds to the database column ad_promotion.carouselPosition
 *
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
private Integer carouselposition;

/**
 * This field was generated by MyBatis Generator.
 * This field corresponds to the database column ad_promotion.startTime
 *
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
private Date starttime;

/**
 * This field was generated by MyBatis Generator.
 * This field corresponds to the database column ad_promotion.endTime
 *
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
private Date endtime;

/**
 * This field was generated by MyBatis Generator.
 * This field corresponds to the database column ad_promotion.createdBy
 *
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
private Long createdby;

/**
 * This field was generated by MyBatis Generator.
 * This field corresponds to the database column ad_promotion.creationDate
 *
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
private Date creationdate;

/**
 * This field was generated by MyBatis Generator.
 * This field corresponds to the database column ad_promotion.modifyBy
 *
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
private Long modifyby;

/**
 * This field was generated by MyBatis Generator.
 * This field corresponds to the database column ad_promotion.modifyDate
 *
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
private Date modifydate;

/**
 * This method was generated by MyBatis Generator.
 * This method returns the value of the database column ad_promotion.id
 *
 * @return the value of ad_promotion.id
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public Long getId () {
    return id;
}

/**
 * This method was generated by MyBatis Generator.
 * This method sets the value of the database column ad_promotion.id
 *
 * @param id the value for ad_promotion.id
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public void setId (Long id) {
    this.id = id;
}

/**
 * This method was generated by MyBatis Generator.
 * This method returns the value of the database column ad_promotion.appId
 *
 * @return the value of ad_promotion.appId
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public Long getAppid () {
    return appid;
}

/**
 * This method was generated by MyBatis Generator.
 * This method sets the value of the database column ad_promotion.appId
 *
 * @param appid the value for ad_promotion.appId
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public void setAppid (Long appid) {
    this.appid = appid;
}

/**
 * This method was generated by MyBatis Generator.
 * This method returns the value of the database column ad_promotion.adPicPath
 *
 * @return the value of ad_promotion.adPicPath
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public String getAdpicpath () {
    return adpicpath;
}

/**
 * This method was generated by MyBatis Generator.
 * This method sets the value of the database column ad_promotion.adPicPath
 *
 * @param adpicpath the value for ad_promotion.adPicPath
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public void setAdpicpath (String adpicpath) {
    this.adpicpath = adpicpath;
}

/**
 * This method was generated by MyBatis Generator.
 * This method returns the value of the database column ad_promotion.adPV
 *
 * @return the value of ad_promotion.adPV
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public Long getAdpv () {
    return adpv;
}

/**
 * This method was generated by MyBatis Generator.
 * This method sets the value of the database column ad_promotion.adPV
 *
 * @param adpv the value for ad_promotion.adPV
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public void setAdpv (Long adpv) {
    this.adpv = adpv;
}

/**
 * This method was generated by MyBatis Generator.
 * This method returns the value of the database column ad_promotion.carouselPosition
 *
 * @return the value of ad_promotion.carouselPosition
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public Integer getCarouselposition () {
    return carouselposition;
}

/**
 * This method was generated by MyBatis Generator.
 * This method sets the value of the database column ad_promotion.carouselPosition
 *
 * @param carouselposition the value for ad_promotion.carouselPosition
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public void setCarouselposition (Integer carouselposition) {
    this.carouselposition = carouselposition;
}

/**
 * This method was generated by MyBatis Generator.
 * This method returns the value of the database column ad_promotion.startTime
 *
 * @return the value of ad_promotion.startTime
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public Date getStarttime () {
    return starttime;
}

/**
 * This method was generated by MyBatis Generator.
 * This method sets the value of the database column ad_promotion.startTime
 *
 * @param starttime the value for ad_promotion.startTime
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public void setStarttime (Date starttime) {
    this.starttime = starttime;
}

/**
 * This method was generated by MyBatis Generator.
 * This method returns the value of the database column ad_promotion.endTime
 *
 * @return the value of ad_promotion.endTime
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public Date getEndtime () {
    return endtime;
}

/**
 * This method was generated by MyBatis Generator.
 * This method sets the value of the database column ad_promotion.endTime
 *
 * @param endtime the value for ad_promotion.endTime
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public void setEndtime (Date endtime) {
    this.endtime = endtime;
}

/**
 * This method was generated by MyBatis Generator.
 * This method returns the value of the database column ad_promotion.createdBy
 *
 * @return the value of ad_promotion.createdBy
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public Long getCreatedby () {
    return createdby;
}

/**
 * This method was generated by MyBatis Generator.
 * This method sets the value of the database column ad_promotion.createdBy
 *
 * @param createdby the value for ad_promotion.createdBy
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public void setCreatedby (Long createdby) {
    this.createdby = createdby;
}

/**
 * This method was generated by MyBatis Generator.
 * This method returns the value of the database column ad_promotion.creationDate
 *
 * @return the value of ad_promotion.creationDate
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public Date getCreationdate () {
    return creationdate;
}

/**
 * This method was generated by MyBatis Generator.
 * This method sets the value of the database column ad_promotion.creationDate
 *
 * @param creationdate the value for ad_promotion.creationDate
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public void setCreationdate (Date creationdate) {
    this.creationdate = creationdate;
}

/**
 * This method was generated by MyBatis Generator.
 * This method returns the value of the database column ad_promotion.modifyBy
 *
 * @return the value of ad_promotion.modifyBy
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public Long getModifyby () {
    return modifyby;
}

/**
 * This method was generated by MyBatis Generator.
 * This method sets the value of the database column ad_promotion.modifyBy
 *
 * @param modifyby the value for ad_promotion.modifyBy
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public void setModifyby (Long modifyby) {
    this.modifyby = modifyby;
}

/**
 * This method was generated by MyBatis Generator.
 * This method returns the value of the database column ad_promotion.modifyDate
 *
 * @return the value of ad_promotion.modifyDate
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public Date getModifydate () {
    return modifydate;
}

/**
 * This method was generated by MyBatis Generator.
 * This method sets the value of the database column ad_promotion.modifyDate
 *
 * @param modifydate the value for ad_promotion.modifyDate
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public void setModifydate (Date modifydate) {
    this.modifydate = modifydate;
}
}