package com.appsys.pojo;

import java.util.Date;

public class DataDictionary {
/**
 * This field was generated by MyBatis Generator.
 * This field corresponds to the database column data_dictionary.id
 *
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
private Long id;

/**
 * This field was generated by MyBatis Generator.
 * This field corresponds to the database column data_dictionary.typeCode
 *
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
private String typecode;

/**
 * This field was generated by MyBatis Generator.
 * This field corresponds to the database column data_dictionary.typeName
 *
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
private String typename;

/**
 * This field was generated by MyBatis Generator.
 * This field corresponds to the database column data_dictionary.valueId
 *
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
private Long valueid;

/**
 * This field was generated by MyBatis Generator.
 * This field corresponds to the database column data_dictionary.valueName
 *
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
private String valuename;

/**
 * This field was generated by MyBatis Generator.
 * This field corresponds to the database column data_dictionary.createdBy
 *
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
private Long createdby;

/**
 * This field was generated by MyBatis Generator.
 * This field corresponds to the database column data_dictionary.creationDate
 *
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
private Date creationdate;

/**
 * This field was generated by MyBatis Generator.
 * This field corresponds to the database column data_dictionary.modifyBy
 *
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
private Long modifyby;

/**
 * This field was generated by MyBatis Generator.
 * This field corresponds to the database column data_dictionary.modifyDate
 *
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
private Date modifydate;

/**
 * This method was generated by MyBatis Generator.
 * This method returns the value of the database column data_dictionary.id
 *
 * @return the value of data_dictionary.id
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public Long getId () {
    return id;
}

/**
 * This method was generated by MyBatis Generator.
 * This method sets the value of the database column data_dictionary.id
 *
 * @param id the value for data_dictionary.id
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public void setId (Long id) {
    this.id = id;
}

/**
 * This method was generated by MyBatis Generator.
 * This method returns the value of the database column data_dictionary.typeCode
 *
 * @return the value of data_dictionary.typeCode
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public String getTypecode () {
    return typecode;
}

/**
 * This method was generated by MyBatis Generator.
 * This method sets the value of the database column data_dictionary.typeCode
 *
 * @param typecode the value for data_dictionary.typeCode
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public void setTypecode (String typecode) {
    this.typecode = typecode;
}

/**
 * This method was generated by MyBatis Generator.
 * This method returns the value of the database column data_dictionary.typeName
 *
 * @return the value of data_dictionary.typeName
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public String getTypename () {
    return typename;
}

/**
 * This method was generated by MyBatis Generator.
 * This method sets the value of the database column data_dictionary.typeName
 *
 * @param typename the value for data_dictionary.typeName
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public void setTypename (String typename) {
    this.typename = typename;
}

/**
 * This method was generated by MyBatis Generator.
 * This method returns the value of the database column data_dictionary.valueId
 *
 * @return the value of data_dictionary.valueId
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public Long getValueid () {
    return valueid;
}

/**
 * This method was generated by MyBatis Generator.
 * This method sets the value of the database column data_dictionary.valueId
 *
 * @param valueid the value for data_dictionary.valueId
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public void setValueid (Long valueid) {
    this.valueid = valueid;
}

/**
 * This method was generated by MyBatis Generator.
 * This method returns the value of the database column data_dictionary.valueName
 *
 * @return the value of data_dictionary.valueName
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public String getValuename () {
    return valuename;
}

/**
 * This method was generated by MyBatis Generator.
 * This method sets the value of the database column data_dictionary.valueName
 *
 * @param valuename the value for data_dictionary.valueName
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public void setValuename (String valuename) {
    this.valuename = valuename;
}

/**
 * This method was generated by MyBatis Generator.
 * This method returns the value of the database column data_dictionary.createdBy
 *
 * @return the value of data_dictionary.createdBy
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public Long getCreatedby () {
    return createdby;
}

/**
 * This method was generated by MyBatis Generator.
 * This method sets the value of the database column data_dictionary.createdBy
 *
 * @param createdby the value for data_dictionary.createdBy
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public void setCreatedby (Long createdby) {
    this.createdby = createdby;
}

/**
 * This method was generated by MyBatis Generator.
 * This method returns the value of the database column data_dictionary.creationDate
 *
 * @return the value of data_dictionary.creationDate
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public Date getCreationdate () {
    return creationdate;
}

/**
 * This method was generated by MyBatis Generator.
 * This method sets the value of the database column data_dictionary.creationDate
 *
 * @param creationdate the value for data_dictionary.creationDate
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public void setCreationdate (Date creationdate) {
    this.creationdate = creationdate;
}

/**
 * This method was generated by MyBatis Generator.
 * This method returns the value of the database column data_dictionary.modifyBy
 *
 * @return the value of data_dictionary.modifyBy
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public Long getModifyby () {
    return modifyby;
}

/**
 * This method was generated by MyBatis Generator.
 * This method sets the value of the database column data_dictionary.modifyBy
 *
 * @param modifyby the value for data_dictionary.modifyBy
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public void setModifyby (Long modifyby) {
    this.modifyby = modifyby;
}

/**
 * This method was generated by MyBatis Generator.
 * This method returns the value of the database column data_dictionary.modifyDate
 *
 * @return the value of data_dictionary.modifyDate
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public Date getModifydate () {
    return modifydate;
}

/**
 * This method was generated by MyBatis Generator.
 * This method sets the value of the database column data_dictionary.modifyDate
 *
 * @param modifydate the value for data_dictionary.modifyDate
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public void setModifydate (Date modifydate) {
    this.modifydate = modifydate;
}
}