package com.appsys.pojo;

import java.util.Date;

public class DevUser {
/**
 * This field was generated by MyBatis Generator.
 * This field corresponds to the database column dev_user.id
 *
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
private Long id;

/**
 * This field was generated by MyBatis Generator.
 * This field corresponds to the database column dev_user.devCode
 *
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
private String devcode;

/**
 * This field was generated by MyBatis Generator.
 * This field corresponds to the database column dev_user.devName
 *
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
private String devname;

/**
 * This field was generated by MyBatis Generator.
 * This field corresponds to the database column dev_user.devPassword
 *
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
private String devpassword;

/**
 * This field was generated by MyBatis Generator.
 * This field corresponds to the database column dev_user.devEmail
 *
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
private String devemail;

/**
 * This field was generated by MyBatis Generator.
 * This field corresponds to the database column dev_user.devInfo
 *
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
private String devinfo;

/**
 * This field was generated by MyBatis Generator.
 * This field corresponds to the database column dev_user.createdBy
 *
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
private Long createdby;

/**
 * This field was generated by MyBatis Generator.
 * This field corresponds to the database column dev_user.creationDate
 *
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
private Date creationdate;

/**
 * This field was generated by MyBatis Generator.
 * This field corresponds to the database column dev_user.modifyBy
 *
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
private Long modifyby;

/**
 * This field was generated by MyBatis Generator.
 * This field corresponds to the database column dev_user.modifyDate
 *
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
private Date modifydate;

/**
 * This method was generated by MyBatis Generator.
 * This method returns the value of the database column dev_user.id
 *
 * @return the value of dev_user.id
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public Long getId () {
    return id;
}

/**
 * This method was generated by MyBatis Generator.
 * This method sets the value of the database column dev_user.id
 *
 * @param id the value for dev_user.id
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public void setId (Long id) {
    this.id = id;
}

/**
 * This method was generated by MyBatis Generator.
 * This method returns the value of the database column dev_user.devCode
 *
 * @return the value of dev_user.devCode
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public String getDevcode () {
    return devcode;
}

/**
 * This method was generated by MyBatis Generator.
 * This method sets the value of the database column dev_user.devCode
 *
 * @param devcode the value for dev_user.devCode
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public void setDevcode (String devcode) {
    this.devcode = devcode;
}

/**
 * This method was generated by MyBatis Generator.
 * This method returns the value of the database column dev_user.devName
 *
 * @return the value of dev_user.devName
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public String getDevname () {
    return devname;
}

/**
 * This method was generated by MyBatis Generator.
 * This method sets the value of the database column dev_user.devName
 *
 * @param devname the value for dev_user.devName
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public void setDevname (String devname) {
    this.devname = devname;
}

/**
 * This method was generated by MyBatis Generator.
 * This method returns the value of the database column dev_user.devPassword
 *
 * @return the value of dev_user.devPassword
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public String getDevpassword () {
    return devpassword;
}

/**
 * This method was generated by MyBatis Generator.
 * This method sets the value of the database column dev_user.devPassword
 *
 * @param devpassword the value for dev_user.devPassword
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public void setDevpassword (String devpassword) {
    this.devpassword = devpassword;
}

/**
 * This method was generated by MyBatis Generator.
 * This method returns the value of the database column dev_user.devEmail
 *
 * @return the value of dev_user.devEmail
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public String getDevemail () {
    return devemail;
}

/**
 * This method was generated by MyBatis Generator.
 * This method sets the value of the database column dev_user.devEmail
 *
 * @param devemail the value for dev_user.devEmail
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public void setDevemail (String devemail) {
    this.devemail = devemail;
}

/**
 * This method was generated by MyBatis Generator.
 * This method returns the value of the database column dev_user.devInfo
 *
 * @return the value of dev_user.devInfo
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public String getDevinfo () {
    return devinfo;
}

/**
 * This method was generated by MyBatis Generator.
 * This method sets the value of the database column dev_user.devInfo
 *
 * @param devinfo the value for dev_user.devInfo
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public void setDevinfo (String devinfo) {
    this.devinfo = devinfo;
}

/**
 * This method was generated by MyBatis Generator.
 * This method returns the value of the database column dev_user.createdBy
 *
 * @return the value of dev_user.createdBy
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public Long getCreatedby () {
    return createdby;
}

/**
 * This method was generated by MyBatis Generator.
 * This method sets the value of the database column dev_user.createdBy
 *
 * @param createdby the value for dev_user.createdBy
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public void setCreatedby (Long createdby) {
    this.createdby = createdby;
}

/**
 * This method was generated by MyBatis Generator.
 * This method returns the value of the database column dev_user.creationDate
 *
 * @return the value of dev_user.creationDate
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public Date getCreationdate () {
    return creationdate;
}

/**
 * This method was generated by MyBatis Generator.
 * This method sets the value of the database column dev_user.creationDate
 *
 * @param creationdate the value for dev_user.creationDate
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public void setCreationdate (Date creationdate) {
    this.creationdate = creationdate;
}

/**
 * This method was generated by MyBatis Generator.
 * This method returns the value of the database column dev_user.modifyBy
 *
 * @return the value of dev_user.modifyBy
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public Long getModifyby () {
    return modifyby;
}

/**
 * This method was generated by MyBatis Generator.
 * This method sets the value of the database column dev_user.modifyBy
 *
 * @param modifyby the value for dev_user.modifyBy
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public void setModifyby (Long modifyby) {
    this.modifyby = modifyby;
}

/**
 * This method was generated by MyBatis Generator.
 * This method returns the value of the database column dev_user.modifyDate
 *
 * @return the value of dev_user.modifyDate
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public Date getModifydate () {
    return modifydate;
}

/**
 * This method was generated by MyBatis Generator.
 * This method sets the value of the database column dev_user.modifyDate
 *
 * @param modifydate the value for dev_user.modifyDate
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
public void setModifydate (Date modifydate) {
    this.modifydate = modifydate;
}
}