package com.appsys.mapper;

import com.appsys.pojo.AppCategory;

public interface AppCategoryMapper {
/**
 * This method was generated by MyBatis Generator.
 * This method corresponds to the database table app_category
 *
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
int deleteByPrimaryKey (Long id);

/**
 * This method was generated by MyBatis Generator.
 * This method corresponds to the database table app_category
 *
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
int insert (AppCategory record);

/**
 * This method was generated by MyBatis Generator.
 * This method corresponds to the database table app_category
 *
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
int insertSelective (AppCategory record);

/**
 * This method was generated by MyBatis Generator.
 * This method corresponds to the database table app_category
 *
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
AppCategory selectByPrimaryKey (Long id);

/**
 * This method was generated by MyBatis Generator.
 * This method corresponds to the database table app_category
 *
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
int updateByPrimaryKeySelective (AppCategory record);

/**
 * This method was generated by MyBatis Generator.
 * This method corresponds to the database table app_category
 *
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
int updateByPrimaryKey (AppCategory record);
}