package com.appsys.mapper;

import com.appsys.pojo.BackendUser;

public interface BackendUserMapper {
/**
 * This method was generated by MyBatis Generator.
 * This method corresponds to the database table backend_user
 *
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
int deleteByPrimaryKey (Long id);

/**
 * This method was generated by MyBatis Generator.
 * This method corresponds to the database table backend_user
 *
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
int insert (BackendUser record);

/**
 * This method was generated by MyBatis Generator.
 * This method corresponds to the database table backend_user
 *
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
int insertSelective (BackendUser record);

/**
 * This method was generated by MyBatis Generator.
 * This method corresponds to the database table backend_user
 *
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
BackendUser selectByPrimaryKey (Long id);

/**
 * This method was generated by MyBatis Generator.
 * This method corresponds to the database table backend_user
 *
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
int updateByPrimaryKeySelective (BackendUser record);

/**
 * This method was generated by MyBatis Generator.
 * This method corresponds to the database table backend_user
 *
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
int updateByPrimaryKey (BackendUser record);
}