package com.appsys.mapper;

import com.appsys.pojo.DevUser;

public interface DevUserMapper {
/**
 * This method was generated by MyBatis Generator.
 * This method corresponds to the database table dev_user
 *
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
int deleteByPrimaryKey (Long id);

/**
 * This method was generated by MyBatis Generator.
 * This method corresponds to the database table dev_user
 *
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
int insert (DevUser record);

/**
 * This method was generated by MyBatis Generator.
 * This method corresponds to the database table dev_user
 *
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
int insertSelective (DevUser record);

/**
 * This method was generated by MyBatis Generator.
 * This method corresponds to the database table dev_user
 *
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
DevUser selectByPrimaryKey (Long id);

/**
 * This method was generated by MyBatis Generator.
 * This method corresponds to the database table dev_user
 *
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
int updateByPrimaryKeySelective (DevUser record);

/**
 * This method was generated by MyBatis Generator.
 * This method corresponds to the database table dev_user
 *
 * @mbggenerated Wed Jun 17 10:11:16 CST 2020
 */
int updateByPrimaryKey (DevUser record);
}